spring.application.name=demo
server.port=${PORT:8080}
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# spring.profiles.active=dev

# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# # spring.data.mongodb.username=demo
# # spring.data.mongodb.password=demo

spring.data.mongodb.uri=mongodb+srv://saurabh:GBfbL9KWW3u1wIdO@cluster0.ezxedtn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb

# #Saying MongoDB to auto Index the Users
# spring.data.mongodb.auto-index-creation=true

# logging.level.com.arkyper.journalApp=DEBUG

# Turning OFF Loggers of a specific Class
# logging.level.com.arkyper.journalApp.service.UserService=OFF

# SETTING LOG at ROOT Level
# logging.level.root=ERROR

# Turning OFF Logs at ROOT Level
# logging.level.root=OFF

weather.api.key=sqZMPXWcpbMcDFmAeqnqYw==8D98fvMUSrLbeAdK

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arkyper.org@gmail.com
spring.mail.password=qmdy ltch null hvuz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# spring.mail.properties.mail.smtp.starttls.required=true

# spring.redis.host=localhost
# spring.redis.port=6379
spring.redis.uri=redis://default:vm2aKf4LH1YI6zi5C27uVqYLpJwPqOaL@redis-11981.crce182.ap-south-1-1.ec2.redns.redis-cloud.com:11981


